//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class AppConstWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(AppConst), typeof(System.Object));
		L.RegFunction("New", _CreateAppConst);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegConstant("PlayerAttackAlarmBloodPercent", 0.200000002980232);
		L.RegConstant("PlayerMoveSpeed_Sec", 5);
		L.RegConstant("PlayerMoveSpeed_Max", 5);
		L.RegConstant("DevelopMode", 1);
		L.RegConstant("FUBEN_REBIRTH_TIME", 5);
		L.RegConstant("FUBEN_ID", 10001);
		L.RegConstant("FUBEN_SCENE_SID", 1017);
		L.RegConstant("WindowLayerInterval", 10);
		L.RegConstant("WindowConstPanelStartLayer", 200);
		L.RegConstant("UseAutoPick", 1);
		L.RegConstant("LocalHotUpdate", 1);
		L.RegConstant("DebugMode", 1);
		L.RegConstant("ResetCanNotPickTime", 1);
		L.RegConstant("ProtectLevel", 30);
		L.RegConstant("RedNameKillValue", 0);
		L.RegConstant("CameraMoveSpeed", 5);
		L.RegConstant("ChaseInterruptTime", 0.300000011920929);
		L.RegConstant("RecordAvatarInfo", 0);
		L.RegVar("RawResName", get_RawResName, null);
		L.RegVar("RawResPath", get_RawResPath, null);
		L.RegConstant("LowFrameRateLimit", 25);
		L.RegConstant("MinimalOtherplayerCount", 10);
		L.RegConstant("ItemAutoPickRadius", 20);
		L.RegConstant("ItemFlyInitSpeed", 5);
		L.RegConstant("ItemFlyAccelerate", 10);
		L.RegConstant("ItemFlyMinDistance", 0.100000001490116);
		L.RegConstant("ItemLandExplodeTime", 0.200000002980232);
		L.RegConstant("GoldThrowTime", 0.800000011920929);
		L.RegConstant("SmallBagGold", 20);
		L.RegConstant("BigBagGold", 50);
		L.RegConstant("MuscleIncreasIntervalTime", 360);
		L.RegConstant("HighTireValueThreshold", 5000);
		L.RegConstant("ExampleMode", 1);
		L.RegConstant("UpdateMode", 0);
		L.RegConstant("AutoWrapMode", 1);
		L.RegConstant("TimerInterval", 1);
		L.RegConstant("GameFrameRate", 30);
		L.RegConstant("UsePbc", 0);
		L.RegConstant("UseLpeg", 0);
		L.RegConstant("UsePbLua", 0);
		L.RegConstant("UseCJson", 0);
		L.RegConstant("UseSproto", 0);
		L.RegConstant("LuaEncode", 0);
		L.RegVar("AppName", get_AppName, null);
		L.RegVar("AppPrefix", get_AppPrefix, null);
		L.RegVar("ExtName", get_ExtName, null);
		L.RegVar("AssetDirname", get_AssetDirname, null);
		L.RegVar("WebUrl", get_WebUrl, null);
		L.RegConstant("TabTargetDistance", 12);
		L.RegConstant("LockTargetDistance", 8);
		L.RegConstant("LostTargetDistance", 15);
		L.RegConstant("PlayerFightAutoSelectDistance", 11);
		L.RegConstant("FubenAutoSelectDistance", 1000);
		L.RegConstant("ItemHeadTitleHeight", 0.150000005960464);
		L.RegConstant("ItemColdTime", 2);
		L.RegVar("shader_NPC", get_shader_NPC, null);
		L.RegVar("shader_Monster", get_shader_Monster, null);
		L.RegVar("shader_Monster_Alpha", get_shader_Monster_Alpha, null);
		L.RegVar("shader_PlayerAlpha", get_shader_PlayerAlpha, null);
		L.RegVar("shader_OtherPlayerAlpha", get_shader_OtherPlayerAlpha, null);
		L.RegVar("shader_Vehicle", get_shader_Vehicle, null);
		L.RegVar("shader_OtherVehicle", get_shader_OtherVehicle, null);
		L.RegVar("shader_Boss", get_shader_Boss, null);
		L.RegVar("shader_Ground", get_shader_Ground, null);
		L.RegVar("shader_GaussianBlur", get_shader_GaussianBlur, null);
		L.RegConstant("bUsePointLight", 0);
		L.RegConstant("HDRBloom", 1);
		L.RegVar("bTestSceneMode", get_bTestSceneMode, set_bTestSceneMode);
		L.RegVar("bDisableGuide", get_bDisableGuide, set_bDisableGuide);
		L.RegVar("bUseNewSync", get_bUseNewSync, set_bUseNewSync);
		L.RegVar("bUseTotalPath", get_bUseTotalPath, set_bUseTotalPath);
		L.RegVar("SyncWindow", get_SyncWindow, set_SyncWindow);
		L.RegVar("UserId", get_UserId, set_UserId);
		L.RegVar("SocketPort", get_SocketPort, set_SocketPort);
		L.RegVar("SocketAddress", get_SocketAddress, set_SocketAddress);
		L.RegVar("referenceResolution", get_referenceResolution, set_referenceResolution);
		L.RegVar("screenMathMode", get_screenMathMode, set_screenMathMode);
		L.RegVar("uiScaleMode", get_uiScaleMode, set_uiScaleMode);
		L.RegVar("ItemColor", get_ItemColor, set_ItemColor);
		L.RegVar("CareerAlias", get_CareerAlias, set_CareerAlias);
		L.RegVar("RoleModelNames", get_RoleModelNames, set_RoleModelNames);
		L.RegVar("matchWidthOrHeight", get_matchWidthOrHeight, null);
		L.RegVar("LuaBasePath", get_LuaBasePath, null);
		L.RegVar("LuaWrapPath", get_LuaWrapPath, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateAppConst(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				AppConst obj = new AppConst();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: AppConst.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_RawResName(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, AppConst.RawResName);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_RawResPath(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, AppConst.RawResPath);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_AppName(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, AppConst.AppName);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_AppPrefix(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, AppConst.AppPrefix);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ExtName(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, AppConst.ExtName);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_AssetDirname(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, AppConst.AssetDirname);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_WebUrl(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, AppConst.WebUrl);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_shader_NPC(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, AppConst.shader_NPC);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_shader_Monster(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, AppConst.shader_Monster);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_shader_Monster_Alpha(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, AppConst.shader_Monster_Alpha);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_shader_PlayerAlpha(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, AppConst.shader_PlayerAlpha);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_shader_OtherPlayerAlpha(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, AppConst.shader_OtherPlayerAlpha);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_shader_Vehicle(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, AppConst.shader_Vehicle);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_shader_OtherVehicle(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, AppConst.shader_OtherVehicle);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_shader_Boss(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, AppConst.shader_Boss);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_shader_Ground(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, AppConst.shader_Ground);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_shader_GaussianBlur(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, AppConst.shader_GaussianBlur);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_bTestSceneMode(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushboolean(L, AppConst.bTestSceneMode);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_bDisableGuide(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushboolean(L, AppConst.bDisableGuide);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_bUseNewSync(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushboolean(L, AppConst.bUseNewSync);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_bUseTotalPath(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushboolean(L, AppConst.bUseTotalPath);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_SyncWindow(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushnumber(L, AppConst.SyncWindow);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_UserId(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, AppConst.UserId);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_SocketPort(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushinteger(L, AppConst.SocketPort);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_SocketAddress(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, AppConst.SocketAddress);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_referenceResolution(IntPtr L)
	{
		try
		{
			ToLua.Push(L, AppConst.referenceResolution);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_screenMathMode(IntPtr L)
	{
		try
		{
			ToLua.Push(L, AppConst.screenMathMode);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_uiScaleMode(IntPtr L)
	{
		try
		{
			ToLua.Push(L, AppConst.uiScaleMode);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ItemColor(IntPtr L)
	{
		try
		{
			ToLua.Push(L, AppConst.ItemColor);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CareerAlias(IntPtr L)
	{
		try
		{
			ToLua.Push(L, AppConst.CareerAlias);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_RoleModelNames(IntPtr L)
	{
		try
		{
			ToLua.Push(L, AppConst.RoleModelNames);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_matchWidthOrHeight(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushnumber(L, AppConst.matchWidthOrHeight);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LuaBasePath(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, AppConst.LuaBasePath);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LuaWrapPath(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, AppConst.LuaWrapPath);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_bTestSceneMode(IntPtr L)
	{
		try
		{
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			AppConst.bTestSceneMode = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_bDisableGuide(IntPtr L)
	{
		try
		{
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			AppConst.bDisableGuide = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_bUseNewSync(IntPtr L)
	{
		try
		{
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			AppConst.bUseNewSync = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_bUseTotalPath(IntPtr L)
	{
		try
		{
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			AppConst.bUseTotalPath = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_SyncWindow(IntPtr L)
	{
		try
		{
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			AppConst.SyncWindow = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_UserId(IntPtr L)
	{
		try
		{
			string arg0 = ToLua.CheckString(L, 2);
			AppConst.UserId = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_SocketPort(IntPtr L)
	{
		try
		{
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			AppConst.SocketPort = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_SocketAddress(IntPtr L)
	{
		try
		{
			string arg0 = ToLua.CheckString(L, 2);
			AppConst.SocketAddress = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_referenceResolution(IntPtr L)
	{
		try
		{
			UnityEngine.Vector2 arg0 = ToLua.ToVector2(L, 2);
			AppConst.referenceResolution = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_screenMathMode(IntPtr L)
	{
		try
		{
			UnityEngine.UI.CanvasScaler.ScreenMatchMode arg0 = (UnityEngine.UI.CanvasScaler.ScreenMatchMode)ToLua.CheckObject(L, 2, typeof(UnityEngine.UI.CanvasScaler.ScreenMatchMode));
			AppConst.screenMathMode = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_uiScaleMode(IntPtr L)
	{
		try
		{
			UnityEngine.UI.CanvasScaler.ScaleMode arg0 = (UnityEngine.UI.CanvasScaler.ScaleMode)ToLua.CheckObject(L, 2, typeof(UnityEngine.UI.CanvasScaler.ScaleMode));
			AppConst.uiScaleMode = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_ItemColor(IntPtr L)
	{
		try
		{
			UnityEngine.Color[] arg0 = ToLua.CheckObjectArray<UnityEngine.Color>(L, 2);
			AppConst.ItemColor = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_CareerAlias(IntPtr L)
	{
		try
		{
			string[] arg0 = ToLua.CheckStringArray(L, 2);
			AppConst.CareerAlias = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_RoleModelNames(IntPtr L)
	{
		try
		{
			string[] arg0 = ToLua.CheckStringArray(L, 2);
			AppConst.RoleModelNames = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

