//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class GameResTypeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(GameResType));
		L.RegVar("Audio", get_Audio, null);
		L.RegVar("Clip", get_Clip, null);
		L.RegVar("Cloth", get_Cloth, null);
		L.RegVar("DropItem", get_DropItem, null);
		L.RegVar("Effect", get_Effect, null);
		L.RegVar("Emote", get_Emote, null);
		L.RegVar("FloatText", get_FloatText, null);
		L.RegVar("Font", get_Font, null);
		L.RegVar("Hair", get_Hair, null);
		L.RegVar("HeadText", get_HeadText, null);
		L.RegVar("Atlas", get_Atlas, null);
		L.RegVar("Item", get_Item, null);
		L.RegVar("Lua", get_Lua, null);
		L.RegVar("Material", get_Material, null);
		L.RegVar("Model", get_Model, null);
		L.RegVar("None", get_None, null);
		L.RegVar("Scene", get_Scene, null);
		L.RegVar("SceneElement", get_SceneElement, null);
		L.RegVar("StateMachine", get_StateMachine, null);
		L.RegVar("Table", get_Table, null);
		L.RegVar("Texture", get_Texture, null);
		L.RegVar("UI", get_UI, null);
		L.RegVar("Weapon", get_Weapon, null);
		L.RegVar("Shader", get_Shader, null);
		L.RegVar("Sprite", get_Sprite, null);
		L.RegVar("EffectElement", get_EffectElement, null);
		L.RegVar("Icon", get_Icon, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Audio(IntPtr L)
	{
		ToLua.Push(L, GameResType.Audio);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Clip(IntPtr L)
	{
		ToLua.Push(L, GameResType.Clip);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Cloth(IntPtr L)
	{
		ToLua.Push(L, GameResType.Cloth);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_DropItem(IntPtr L)
	{
		ToLua.Push(L, GameResType.DropItem);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Effect(IntPtr L)
	{
		ToLua.Push(L, GameResType.Effect);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Emote(IntPtr L)
	{
		ToLua.Push(L, GameResType.Emote);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_FloatText(IntPtr L)
	{
		ToLua.Push(L, GameResType.FloatText);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Font(IntPtr L)
	{
		ToLua.Push(L, GameResType.Font);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Hair(IntPtr L)
	{
		ToLua.Push(L, GameResType.Hair);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_HeadText(IntPtr L)
	{
		ToLua.Push(L, GameResType.HeadText);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Atlas(IntPtr L)
	{
		ToLua.Push(L, GameResType.Atlas);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Item(IntPtr L)
	{
		ToLua.Push(L, GameResType.Item);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Lua(IntPtr L)
	{
		ToLua.Push(L, GameResType.Lua);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Material(IntPtr L)
	{
		ToLua.Push(L, GameResType.Material);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Model(IntPtr L)
	{
		ToLua.Push(L, GameResType.Model);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_None(IntPtr L)
	{
		ToLua.Push(L, GameResType.None);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Scene(IntPtr L)
	{
		ToLua.Push(L, GameResType.Scene);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_SceneElement(IntPtr L)
	{
		ToLua.Push(L, GameResType.SceneElement);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_StateMachine(IntPtr L)
	{
		ToLua.Push(L, GameResType.StateMachine);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Table(IntPtr L)
	{
		ToLua.Push(L, GameResType.Table);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Texture(IntPtr L)
	{
		ToLua.Push(L, GameResType.Texture);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_UI(IntPtr L)
	{
		ToLua.Push(L, GameResType.UI);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Weapon(IntPtr L)
	{
		ToLua.Push(L, GameResType.Weapon);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Shader(IntPtr L)
	{
		ToLua.Push(L, GameResType.Shader);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Sprite(IntPtr L)
	{
		ToLua.Push(L, GameResType.Sprite);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EffectElement(IntPtr L)
	{
		ToLua.Push(L, GameResType.EffectElement);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Icon(IntPtr L)
	{
		ToLua.Push(L, GameResType.Icon);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		GameResType o = (GameResType)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

