//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class ShakeCameraTypeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(ShakeCameraType));
		L.RegVar("None", get_None, null);
		L.RegVar("DOWN_UP", get_DOWN_UP, null);
		L.RegVar("FAR_NEAR", get_FAR_NEAR, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_None(IntPtr L)
	{
		ToLua.Push(L, ShakeCameraType.None);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_DOWN_UP(IntPtr L)
	{
		ToLua.Push(L, ShakeCameraType.DOWN_UP);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_FAR_NEAR(IntPtr L)
	{
		ToLua.Push(L, ShakeCameraType.FAR_NEAR);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		ShakeCameraType o = (ShakeCameraType)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

