//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Singleton_GameUpdaterWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Singleton<GameUpdater>), typeof(System.Object), "Singleton_GameUpdater");
		L.RegFunction("Update", Update);
		L.RegFunction("Reset", Reset);
		L.RegFunction("New", _CreateSingleton_GameUpdater);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Instance", get_Instance, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateSingleton_GameUpdater(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				Singleton<GameUpdater> obj = new Singleton<GameUpdater>();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: Singleton<GameUpdater>.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Update(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Singleton<GameUpdater> obj = (Singleton<GameUpdater>)ToLua.CheckObject(L, 1, typeof(Singleton<GameUpdater>));
			obj.Update();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Reset(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Singleton<GameUpdater> obj = (Singleton<GameUpdater>)ToLua.CheckObject(L, 1, typeof(Singleton<GameUpdater>));
			obj.Reset();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Instance(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, Singleton<GameUpdater>.Instance);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

