//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UIOpenTypeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UIOpenType));
		L.RegVar("NONE", get_NONE, null);
		L.RegVar("CLOSEOTHER", get_CLOSEOTHER, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_NONE(IntPtr L)
	{
		ToLua.Push(L, UIOpenType.NONE);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CLOSEOTHER(IntPtr L)
	{
		ToLua.Push(L, UIOpenType.CLOSEOTHER);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		UIOpenType o = (UIOpenType)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

