//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_NetworkReachabilityWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.NetworkReachability));
		L.RegVar("NotReachable", get_NotReachable, null);
		L.RegVar("ReachableViaCarrierDataNetwork", get_ReachableViaCarrierDataNetwork, null);
		L.RegVar("ReachableViaLocalAreaNetwork", get_ReachableViaLocalAreaNetwork, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_NotReachable(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.NetworkReachability.NotReachable);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ReachableViaCarrierDataNetwork(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.NetworkReachability.ReachableViaCarrierDataNetwork);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ReachableViaLocalAreaNetwork(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.NetworkReachability.ReachableViaLocalAreaNetwork);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		UnityEngine.NetworkReachability o = (UnityEngine.NetworkReachability)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

