//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class WindowLayerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(WindowLayer));
		L.RegVar("None", get_None, null);
		L.RegVar("UNDER_PANEL", get_UNDER_PANEL, null);
		L.RegVar("SECOND_LEVEL_PANEL", get_SECOND_LEVEL_PANEL, null);
		L.RegVar("CONST_PANEL", get_CONST_PANEL, null);
		L.RegVar("FULL_SCREEN_PANEL", get_FULL_SCREEN_PANEL, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_None(IntPtr L)
	{
		ToLua.Push(L, WindowLayer.None);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_UNDER_PANEL(IntPtr L)
	{
		ToLua.Push(L, WindowLayer.UNDER_PANEL);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_SECOND_LEVEL_PANEL(IntPtr L)
	{
		ToLua.Push(L, WindowLayer.SECOND_LEVEL_PANEL);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CONST_PANEL(IntPtr L)
	{
		ToLua.Push(L, WindowLayer.CONST_PANEL);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_FULL_SCREEN_PANEL(IntPtr L)
	{
		ToLua.Push(L, WindowLayer.FULL_SCREEN_PANEL);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		WindowLayer o = (WindowLayer)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

