
tb.ItemTable =  {
[10000001] =  {tid = 10000001,name = "金币",showtype = "货币",item_type = 4,level = 1,
            show_type = "normalItem", show_name = "金币",quality = 0,level_limit = 1,max_count = 1,
            icon = "tb_jinbi_wupin",could_sell = true,could_use = false,could_trade = true,price = 0,effect = 0,
            cd = 0,cd_group = 0,priority = 2,use_effect = "大陆通用的货币，用途广泛",
            describe = ""
            },
[10000002] =  {tid = 10000002,name = "钻石",showtype = "货币",item_type = 4,level = 1,
            show_type = "normalItem", show_name = "钻石",quality = 0,level_limit = 1,max_count = 999,
            icon = "tb_zuanshi_wupin",could_sell = false,could_use = false,could_trade = false,price = 0,effect = 0,
            cd = 0,cd_group = 0,priority = 2,use_effect = "极其珍贵稀有的钻石",
            describe = ""
            },
[10000003] =  {tid = 10000003,name = "魔龙之心",showtype = "材料",item_type = 9,level = 40,
            show_type = "normalItem", show_name = "魔龙之心",quality = 3,level_limit = 40,max_count = 999,
            icon = "tb_molongzhixin",could_sell = false,could_use = false,could_trade = false,price = 0,effect = 0,
            cd = 0,cd_group = 0,priority = 1500,use_effect = "上古魔龙的灵魂核心，蕴含能量，可用于在魔龙岛商人处兑换物品",
            describe = ""
            },
[10005001] =  {tid = 10005001,name = "狂怒骑士的秘宝",showtype = "特殊",item_type = 6,level = 35,
            show_type = "giftBox", show_name = "狂怒骑士的秘宝",quality = 3,level_limit = 1,max_count = 1,
            icon = "tb_gaojibaoxiang",could_sell = false,could_use = true,could_trade = false,price = 0,effect = 1,
            cd = 0,cd_group = 0,priority = 1000,use_effect = "这是你击败狂怒骑士后获得的奖赏，使用后可获得20级高品质装备",
            describe = ""
            },
[10005002] =  {tid = 10005002,name = "狂怒骑士的遗物",showtype = "特殊",item_type = 6,level = 35,
            show_type = "giftBox", show_name = "狂怒骑士的遗物",quality = 2,level_limit = 1,max_count = 1,
            icon = "tb_dijibaoxiang",could_sell = false,could_use = true,could_trade = false,price = 0,effect = 1,
            cd = 0,cd_group = 0,priority = 1001,use_effect = "这是你击败狂怒骑士后获得的奖赏，使用后可获得20级高品质装备",
            describe = ""
            },
[10005003] =  {tid = 10005003,name = "沙海死神的秘宝",showtype = "特殊",item_type = 6,level = 45,
            show_type = "giftBox", show_name = "沙海死神的秘宝",quality = 3,level_limit = 1,max_count = 1,
            icon = "tb_gaojibaoxiang",could_sell = false,could_use = true,could_trade = false,price = 0,effect = 1,
            cd = 0,cd_group = 0,priority = 1000,use_effect = "这是你击败沙海死神后获得的奖赏，使用后可获得40级高品质装备",
            describe = ""
            },
[10005004] =  {tid = 10005004,name = "沙海死神的遗物",showtype = "特殊",item_type = 6,level = 45,
            show_type = "giftBox", show_name = "沙海死神的遗物",quality = 2,level_limit = 1,max_count = 1,
            icon = "tb_dijibaoxiang",could_sell = false,could_use = true,could_trade = false,price = 0,effect = 1,
            cd = 0,cd_group = 0,priority = 1001,use_effect = "这是你击败沙海死神后获得的奖赏，使用后可获得40级高品质装备",
            describe = ""
            },
[10005005] =  {tid = 10005005,name = "寂静海王的秘宝",showtype = "特殊",item_type = 6,level = 55,
            show_type = "giftBox", show_name = "寂静海王的秘宝",quality = 3,level_limit = 1,max_count = 1,
            icon = "tb_gaojibaoxiang",could_sell = false,could_use = true,could_trade = false,price = 0,effect = 1,
            cd = 0,cd_group = 0,priority = 1000,use_effect = "这是你击败寂静海王后获得的奖赏，使用后可获得50级高品质装备",
            describe = ""
            },
[10005006] =  {tid = 10005006,name = "寂静海王的遗物",showtype = "特殊",item_type = 6,level = 55,
            show_type = "giftBox", show_name = "寂静海王的遗物",quality = 2,level_limit = 1,max_count = 1,
            icon = "tb_dijibaoxiang",could_sell = false,could_use = true,could_trade = false,price = 0,effect = 1,
            cd = 0,cd_group = 0,priority = 1001,use_effect = "这是你击败寂静海王后获得的奖赏，使用后可获得50级高品质装备",
            describe = ""
            },
[10010001] =  {tid = 10010001,name = "悬赏刷新令",showtype = "材料",item_type = 5,level = 1,
            show_type = "normalItem", show_name = "悬赏刷新令",quality = 2,level_limit = 1,max_count = 999,
            icon = "tb_shuaxinling",could_sell = true,could_use = false,could_trade = false,price = 100,effect = 0,
            cd = 0,cd_group = 0,priority = 1700,use_effect = "刷新悬赏任务品质，悬赏任务品质分为D/C/B/A/S，品质越高，完成后奖励越高",
            describe = ""
            },
[10010002] =  {tid = 10010002,name = "传送卷轴",showtype = "材料",item_type = 2,level = 1,
            show_type = "normalItem", show_name = "传送卷轴",quality = 3,level_limit = 1,max_count = 99,
            icon = "tb_chuansongjuanzhou",could_sell = true,could_use = false,could_trade = true,price = 100,effect = 1,
            cd = 0,cd_group = 0,priority = 1600,use_effect = "“凡是魔法可以流动的地方，都将留下我的足迹”——这个神秘的卷轴可以让你立即抵达自动寻路的目的地",
            describe = ""
            },
[10010003] =  {tid = 10010003,name = "扫荡券",showtype = "材料",item_type = 7,level = 1,
            show_type = "normalItem", show_name = "扫荡券",quality = 3,level_limit = 1,max_count = 999,
            icon = "tb_saodanjuan",could_sell = true,could_use = false,could_trade = true,price = 100,effect = 0,
            cd = 0,cd_group = 0,priority = 1800,use_effect = "由魔纹者组织发放的稀有票券，用于快速通过副本",
            describe = ""
            },
[10010004] =  {tid = 10010004,name = "地狱副本门票",showtype = "材料",item_type = 7,level = 1,
            show_type = "normalItem", show_name = "地狱副本门票",quality = 3,level_limit = 1,max_count = 99,
            icon = "tb_diyumenpiao",could_sell = true,could_use = false,could_trade = true,price = 100,effect = 0,
            cd = 0,cd_group = 0,priority = 1400,use_effect = "“敢来地狱副本挑战我吗？我会让你知道地狱为何被称之为地狱”",
            describe = ""
            },
[10010005] =  {tid = 10010005,name = "金钥匙",showtype = "材料",item_type = 7,level = 35,
            show_type = "normalItem", show_name = "金钥匙",quality = 4,level_limit = 35,max_count = 999,
            icon = "tb_jinyaoshi",could_sell = true,could_use = false,could_trade = false,price = 100,effect = 0,
            cd = 0,cd_group = 0,priority = 1100,use_effect = "拥有神秘力量，可以开启高级宝库的钥匙",
            describe = ""
            },
[10010006] =  {tid = 10010006,name = "金钥匙碎片一",showtype = "材料",item_type = 10,level = 35,
            show_type = "normalItem", show_name = "金钥匙碎片一",quality = 4,level_limit = 35,max_count = 999,
            icon = "tb_jinyaoshi_1",could_sell = true,could_use = false,could_trade = false,price = 20,effect = 0,
            cd = 0,cd_group = 0,priority = 1101,use_effect = "收集金钥匙碎片一、二、三可以合成一把金钥匙，获得非常丰厚的宝藏",
            describe = ""
            },
[10010007] =  {tid = 10010007,name = "金钥匙碎片二",showtype = "材料",item_type = 10,level = 35,
            show_type = "normalItem", show_name = "金钥匙碎片二",quality = 4,level_limit = 35,max_count = 999,
            icon = "tb_jinyaoshi_2",could_sell = true,could_use = false,could_trade = false,price = 20,effect = 0,
            cd = 0,cd_group = 0,priority = 1102,use_effect = "收集金钥匙碎片一、二、三可以合成一把金钥匙，获得非常丰厚的宝藏",
            describe = ""
            },
[10010008] =  {tid = 10010008,name = "金钥匙碎片三",showtype = "材料",item_type = 10,level = 35,
            show_type = "normalItem", show_name = "金钥匙碎片三",quality = 4,level_limit = 35,max_count = 999,
            icon = "tb_jinyaoshi_3",could_sell = true,could_use = false,could_trade = false,price = 20,effect = 0,
            cd = 0,cd_group = 0,priority = 1103,use_effect = "收集金钥匙碎片一、二、三可以合成一把金钥匙，获得非常丰厚的宝藏",
            describe = ""
            },
[10010009] =  {tid = 10010009,name = "银钥匙",showtype = "材料",item_type = 7,level = 35,
            show_type = "normalItem", show_name = "银钥匙",quality = 3,level_limit = 35,max_count = 999,
            icon = "tb_yinyaoshi",could_sell = true,could_use = false,could_trade = false,price = 100,effect = 0,
            cd = 0,cd_group = 0,priority = 1104,use_effect = "拥有神秘力量，可以开启宝库的钥匙",
            describe = ""
            },
[10010010] =  {tid = 10010010,name = "银钥匙碎片一",showtype = "材料",item_type = 10,level = 35,
            show_type = "normalItem", show_name = "银钥匙碎片一",quality = 3,level_limit = 35,max_count = 999,
            icon = "tb_yinyaoshi_1",could_sell = true,could_use = false,could_trade = false,price = 20,effect = 0,
            cd = 0,cd_group = 0,priority = 1105,use_effect = "收集银钥匙碎片一、二、三可以合成一把银钥匙，获得宝藏",
            describe = ""
            },
[10010011] =  {tid = 10010011,name = "银钥匙碎片二",showtype = "材料",item_type = 10,level = 35,
            show_type = "normalItem", show_name = "银钥匙碎片二",quality = 3,level_limit = 35,max_count = 999,
            icon = "tb_yinyaoshi_2",could_sell = true,could_use = false,could_trade = false,price = 20,effect = 0,
            cd = 0,cd_group = 0,priority = 1106,use_effect = "收集银钥匙碎片一、二、三可以合成一把银钥匙，获得宝藏",
            describe = ""
            },
[10010012] =  {tid = 10010012,name = "银钥匙碎片三",showtype = "材料",item_type = 10,level = 35,
            show_type = "normalItem", show_name = "银钥匙碎片三",quality = 3,level_limit = 35,max_count = 999,
            icon = "tb_yinyaoshi_3",could_sell = true,could_use = false,could_trade = false,price = 20,effect = 0,
            cd = 0,cd_group = 0,priority = 1107,use_effect = "收集银钥匙碎片一、二、三可以合成一把银钥匙，获得宝藏",
            describe = ""
            },
[10010013] =  {tid = 10010013,name = "复活卷轴",showtype = "材料",item_type = 7,level = 1,
            show_type = "normalItem", show_name = "复活卷轴",quality = 3,level_limit = 1,max_count = 999,
            icon = "tb_fuhuoquan",could_sell = true,could_use = false,could_trade = true,price = 100,effect = 0,
            cd = 0,cd_group = 0,priority = 1601,use_effect = "用于原地复活使用的卷轴，上边用符文之语写道“灵魂，回到我这里来！”",
            describe = ""
            },
[10010014] =  {tid = 10010014,name = "背包扩容卷轴",showtype = "材料",item_type = 7,level = 1,
            show_type = "normalItem", show_name = "背包扩容卷轴",quality = 3,level_limit = 1,max_count = 999,
            icon = "tb_jinshengling",could_sell = true,could_use = false,could_trade = false,price = 1000,effect = 0,
            cd = 0,cd_group = 0,priority = 2000,use_effect = "“基于亚空间技术制作”——用于扩展背包容量上限，点击未解锁的背包格子可查看解锁所需的卷轴数量",
            describe = ""
            },
[10020001] =  {tid = 10020001,name = "饲料",showtype = "材料",item_type = 32,level = 1,
            show_type = "normalItem", show_name = "饲料",quality = 2,level_limit = 40,max_count = 999,
            icon = "tb_siliao",could_sell = true,could_use = true,could_trade = false,price = 10,effect = 0,
            cd = 0,cd_group = 0,priority = 1300,use_effect = "消耗饲料培养坐骑的星级以提升能力",
            describe = ""
            },
[10020002] =  {tid = 10020002,name = "兽魂",showtype = "材料",item_type = 32,level = 1,
            show_type = "normalItem", show_name = "兽魂",quality = 3,level_limit = 40,max_count = 999,
            icon = "tb_shouhun",could_sell = true,could_use = true,could_trade = false,price = 10,effect = 0,
            cd = 0,cd_group = 0,priority = 1301,use_effect = "消耗兽魂进行坐骑进阶，坐骑进阶后能带来更强的能力提升",
            describe = ""
            },
[10020003] =  {tid = 10020003,name = "强化石",showtype = "材料",item_type = 31,level = 1,
            show_type = "normalItem", show_name = "强化石",quality = 2,level_limit = 1,max_count = 999999,
            icon = "tb_gaizaoshi",could_sell = true,could_use = true,could_trade = true,price = 10,effect = 0,
            cd = 0,cd_group = 0,priority = 1200,use_effect = "强化装备时所需的材料，可提高装备的能力",
            describe = ""
            },
[10020004] =  {tid = 10020004,name = "离线挂机时间",showtype = "特殊",item_type = 4,level = 1,
            show_type = "normalItem", show_name = "离线挂机时间",quality = 0,level_limit = 1,max_count = 1,
            icon = "tb_lixianguajishichang",could_sell = false,could_use = true,could_trade = false,price = 0,effect = 0,
            cd = 0,cd_group = 0,priority = 2,use_effect = "可增加离线挂机时间7小时",
            describe = ""
            },
[10020005] =  {tid = 10020005,name = "经验",showtype = "特殊",item_type = 4,level = 1,
            show_type = "normalItem", show_name = "经验",quality = 0,level_limit = 1,max_count = 1,
            icon = "tb_exp",could_sell = false,could_use = true,could_trade = false,price = 0,effect = 0,
            cd = 0,cd_group = 0,priority = 2,use_effect = "可增加经验",
            describe = ""
            },
[10020006] =  {tid = 10020006,name = "贤者之石",showtype = "材料",item_type = 7,level = 1,
            show_type = "normalItem", show_name = "贤者之石",quality = 4,level_limit = 1,max_count = 999,
            icon = "tb_gaizaoshi",could_sell = true,could_use = true,could_trade = true,price = 10,effect = 0,
            cd = 0,cd_group = 0,priority = 1200,use_effect = "使用后获得1点技能点，每个角色最多使用15次",
            describe = ""
            },
[10020007] =  {tid = 10020007,name = "星之尘",showtype = "材料",item_type = 7,level = 1,
            show_type = "normalItem", show_name = "星之尘",quality = 2,level_limit = 1,max_count = 999,
            icon = "tb_xingzhicheng",could_sell = true,could_use = true,could_trade = true,price = 10,effect = 0,
            cd = 0,cd_group = 0,priority = 1200,use_effect = "以众星之力研磨成的粉末，拥有提升神力的作用",
            describe = ""
            },
[10020008] =  {tid = 10020008,name = "月之尘",showtype = "材料",item_type = 7,level = 1,
            show_type = "normalItem", show_name = "月之尘",quality = 3,level_limit = 1,max_count = 999,
            icon = "tb_yuezhicheng",could_sell = true,could_use = true,could_trade = true,price = 10,effect = 0,
            cd = 0,cd_group = 0,priority = 1200,use_effect = "以月光之力研磨成的粉末，拥有提升神力的作用",
            describe = ""
            },
[10052001] =  {tid = 10052001,name = "普通的巫师宝藏",showtype = "巫师宝藏",item_type = 11,level = 20,
            show_type = "normalItem", show_name = "普通的巫师宝藏",quality = 2,level_limit = 1,max_count = 1,
            icon = "tb_baoxiang1",could_sell = false,could_use = false,could_trade = false,price = 10,effect = 0,
            cd = 0,cd_group = 0,priority = 1200,use_effect = "贪婪的萨迦从世界各地收集的珍贵宝藏，开启可以获得大量财宝",
            describe = ""
            },
[10052002] =  {tid = 10052002,name = "稀有的巫师宝藏",showtype = "巫师宝藏",item_type = 11,level = 20,
            show_type = "normalItem", show_name = "稀有的巫师宝藏",quality = 3,level_limit = 1,max_count = 1,
            icon = "tb_baoxiang2",could_sell = false,could_use = false,could_trade = false,price = 10,effect = 0,
            cd = 0,cd_group = 0,priority = 1200,use_effect = "贪婪的萨迦从世界各地收集的珍贵宝藏，开启可以获得大量财宝",
            describe = ""
            },
[10052003] =  {tid = 10052003,name = "史诗的巫师宝藏",showtype = "巫师宝藏",item_type = 11,level = 20,
            show_type = "normalItem", show_name = "史诗的巫师宝藏",quality = 4,level_limit = 1,max_count = 1,
            icon = "tb_baoxiang3",could_sell = false,could_use = false,could_trade = false,price = 10,effect = 0,
            cd = 0,cd_group = 0,priority = 1200,use_effect = "贪婪的萨迦从世界各地收集的珍贵宝藏，开启可以获得大量财宝",
            describe = ""
            },
[10053001] =  {tid = 10053001,name = "普通的巫师宝藏",showtype = "巫师宝藏",item_type = 11,level = 30,
            show_type = "normalItem", show_name = "普通的巫师宝藏",quality = 2,level_limit = 1,max_count = 1,
            icon = "tb_baoxiang1",could_sell = false,could_use = false,could_trade = false,price = 10,effect = 0,
            cd = 0,cd_group = 0,priority = 1200,use_effect = "贪婪的萨迦从世界各地收集的珍贵宝藏，开启可以获得大量财宝",
            describe = ""
            },
[10053002] =  {tid = 10053002,name = "稀有的巫师宝藏",showtype = "巫师宝藏",item_type = 11,level = 30,
            show_type = "normalItem", show_name = "稀有的巫师宝藏",quality = 3,level_limit = 1,max_count = 1,
            icon = "tb_baoxiang2",could_sell = false,could_use = false,could_trade = false,price = 10,effect = 0,
            cd = 0,cd_group = 0,priority = 1200,use_effect = "贪婪的萨迦从世界各地收集的珍贵宝藏，开启可以获得大量财宝",
            describe = ""
            },
[10053003] =  {tid = 10053003,name = "史诗的巫师宝藏",showtype = "巫师宝藏",item_type = 11,level = 30,
            show_type = "normalItem", show_name = "史诗的巫师宝藏",quality = 4,level_limit = 1,max_count = 1,
            icon = "tb_baoxiang3",could_sell = false,could_use = false,could_trade = false,price = 10,effect = 0,
            cd = 0,cd_group = 0,priority = 1200,use_effect = "贪婪的萨迦从世界各地收集的珍贵宝藏，开启可以获得大量财宝",
            describe = ""
            },
[10054001] =  {tid = 10054001,name = "普通的巫师宝藏",showtype = "巫师宝藏",item_type = 11,level = 40,
            show_type = "normalItem", show_name = "普通的巫师宝藏",quality = 2,level_limit = 1,max_count = 1,
            icon = "tb_baoxiang1",could_sell = false,could_use = false,could_trade = false,price = 10,effect = 0,
            cd = 0,cd_group = 0,priority = 1200,use_effect = "贪婪的萨迦从世界各地收集的珍贵宝藏，开启可以获得大量财宝",
            describe = ""
            },
[10054002] =  {tid = 10054002,name = "稀有的巫师宝藏",showtype = "巫师宝藏",item_type = 11,level = 40,
            show_type = "normalItem", show_name = "稀有的巫师宝藏",quality = 3,level_limit = 1,max_count = 1,
            icon = "tb_baoxiang2",could_sell = false,could_use = false,could_trade = false,price = 10,effect = 0,
            cd = 0,cd_group = 0,priority = 1200,use_effect = "贪婪的萨迦从世界各地收集的珍贵宝藏，开启可以获得大量财宝",
            describe = ""
            },
[10054003] =  {tid = 10054003,name = "史诗的巫师宝藏",showtype = "巫师宝藏",item_type = 11,level = 40,
            show_type = "normalItem", show_name = "史诗的巫师宝藏",quality = 4,level_limit = 1,max_count = 1,
            icon = "tb_baoxiang3",could_sell = false,could_use = false,could_trade = false,price = 10,effect = 0,
            cd = 0,cd_group = 0,priority = 1200,use_effect = "贪婪的萨迦从世界各地收集的珍贵宝藏，开启可以获得大量财宝",
            describe = ""
            },
[10055001] =  {tid = 10055001,name = "普通的巫师宝藏",showtype = "巫师宝藏",item_type = 11,level = 50,
            show_type = "normalItem", show_name = "普通的巫师宝藏",quality = 2,level_limit = 1,max_count = 1,
            icon = "tb_baoxiang1",could_sell = false,could_use = false,could_trade = false,price = 10,effect = 0,
            cd = 0,cd_group = 0,priority = 1200,use_effect = "贪婪的萨迦从世界各地收集的珍贵宝藏，开启可以获得大量财宝",
            describe = ""
            },
[10055002] =  {tid = 10055002,name = "稀有的巫师宝藏",showtype = "巫师宝藏",item_type = 11,level = 50,
            show_type = "normalItem", show_name = "稀有的巫师宝藏",quality = 3,level_limit = 1,max_count = 1,
            icon = "tb_baoxiang2",could_sell = false,could_use = false,could_trade = false,price = 10,effect = 0,
            cd = 0,cd_group = 0,priority = 1200,use_effect = "贪婪的萨迦从世界各地收集的珍贵宝藏，开启可以获得大量财宝",
            describe = ""
            },
[10055003] =  {tid = 10055003,name = "史诗的巫师宝藏",showtype = "巫师宝藏",item_type = 11,level = 50,
            show_type = "normalItem", show_name = "史诗的巫师宝藏",quality = 4,level_limit = 1,max_count = 1,
            icon = "tb_baoxiang3",could_sell = false,could_use = false,could_trade = false,price = 10,effect = 0,
            cd = 0,cd_group = 0,priority = 1200,use_effect = "贪婪的萨迦从世界各地收集的珍贵宝藏，开启可以获得大量财宝",
            describe = ""
            },
[10056001] =  {tid = 10056001,name = "普通的巫师宝藏",showtype = "巫师宝藏",item_type = 11,level = 60,
            show_type = "normalItem", show_name = "普通的巫师宝藏",quality = 2,level_limit = 1,max_count = 1,
            icon = "tb_baoxiang1",could_sell = false,could_use = false,could_trade = false,price = 10,effect = 0,
            cd = 0,cd_group = 0,priority = 1200,use_effect = "贪婪的萨迦从世界各地收集的珍贵宝藏，开启可以获得大量财宝",
            describe = ""
            },
[10056002] =  {tid = 10056002,name = "稀有的巫师宝藏",showtype = "巫师宝藏",item_type = 11,level = 60,
            show_type = "normalItem", show_name = "稀有的巫师宝藏",quality = 3,level_limit = 1,max_count = 1,
            icon = "tb_baoxiang2",could_sell = false,could_use = false,could_trade = false,price = 10,effect = 0,
            cd = 0,cd_group = 0,priority = 1200,use_effect = "贪婪的萨迦从世界各地收集的珍贵宝藏，开启可以获得大量财宝",
            describe = ""
            },
[10056003] =  {tid = 10056003,name = "史诗的巫师宝藏",showtype = "巫师宝藏",item_type = 11,level = 60,
            show_type = "normalItem", show_name = "史诗的巫师宝藏",quality = 4,level_limit = 1,max_count = 1,
            icon = "tb_baoxiang3",could_sell = false,could_use = false,could_trade = false,price = 10,effect = 0,
            cd = 0,cd_group = 0,priority = 1200,use_effect = "贪婪的萨迦从世界各地收集的珍贵宝藏，开启可以获得大量财宝",
            describe = ""
            }
}
tb.GenIndexTable("ItemTable", "name")