tb.DailyActTable = {

		[100001] = {
			id = 100001,
			name = "悬赏",
			priority = 1,
			left_top = "tb_act_tuijian",
			type = 1,
			icon = "tb_exp",
			level = 30,
			condition = 25,
			form = "单人/组队",
			award = "经验值",
			show_name = "全天",
			active_value = 15,
			total_value = 75,
			times = 5,
			text = "完成各项悬赏任务获取高额经验，刷新悬赏任务不会降低任务品质！",
			awardicon = "tb_exp",
		},
		
		[100002] = {
			id = 100002,
			name = "藏宝图",
			priority = 2,
			left_top = "tb_act_tuijian",
			type = 1,
			icon = "tb_jinbi_wupin",
			level = 35,
			condition = 30,
			form = "单人",
			award = "宝石，金币",
			show_name = "全天",
			active_value = 15,
			total_value = 75,
			times = 5,
			text = "前往世界各地寻找上古宝藏，获得大量金币奖励！",
			awardicon = "tb_jinbi_wupin，tb_hongbaoshi_1",
		},
		
		[100004] = {
			id = 100004,
			name = "魔龙岛",
			priority = 3,
			type = 1,
			icon = "tb_molongzhixin",
			level = 40,
			condition = 35,
			form = "单人",
			award = "魔龙之心，经验值，钻石，金币",
			show_name = "全天",
			active_value = 15,
			total_value = 60,
			times = 4,
			text = "完成魔龙岛各项任务，获取丰厚奖励！",
			awardicon = "tb_molongzhixin，tb_exp，tb_zuanshi_wupin，tb_jinbi_wupin",
		},
		
		[100003] = {
			id = 100003,
			name = "试炼秘境",
			priority = 4,
			type = 1,
			icon = "tb_tongyongzuangbei",
			level = 40,
			condition = 35,
			form = "组队",
			award = "经验，装备",
			show_name = "全天",
			active_value = 5,
			total_value = 15,
			times = 3,
			text = "重现曾经挑战过的副本，再次与BOSS英勇战斗吧！",
			awardicon = "tb_exp，tb_tongyongzuangbei",
		},
		
		[100005] = {
			id = 100005,
			name = "魔龙除恶",
			priority = 5,
			type = 1,
			icon = "tb_molongzhixin",
			level = 40,
			condition = 35,
			form = "单人/组队",
			award = "魔龙之心，经验",
			show_name = "全天",
			active_value = 15,
			total_value = 15,
			times = 300,
			text = "魔龙岛怪物死亡后掉落重要物品魔龙之心，可用于在魔龙岛商店换取珍稀物品！",
			awardicon = "tb_molongzhixin，tb_exp",
		},
		
		[100006] = {
			id = 100006,
			name = "野外挂机",
			priority = 6,
			type = 1,
			icon = "tb_exp",
			level = 1,
			condition = 1,
			form = "单人",
			award = "经验，金币，装备",
			show_name = "全天",
			text = "自动前往适合当前角色能力的怪区进行挂机，经验、装备两不误！",
			awardicon = "tb_exp，tb_jinbi_wupin，tb_tongyongzuangbei",
		},
		
		[100007] = {
			id = 100007,
			name = "离线挂机",
			priority = 7,
			type = 1,
			icon = "tb_exp",
			level = 30,
			condition = 25,
			form = "单人",
			award = "经验，金币，装备",
			show_name = "全天",
			text = "离线10分钟后，自动前往适合当前角色能力的怪区进行离线挂机，离线依然能打怪升级！",
			awardicon = "tb_exp，tb_jinbi_wupin，tb_tongyongzuangbei",
		},
		
		[100008] = {
			id = 100008,
			name = "怪物头目",
			priority = 8,
			type = 1,
			icon = "tb_tongyongzuangbei",
			level = 99,
			condition = 99,
			form = "单人/组队",
			award = "强化石，橙装碎片，装备",
			show_name = "全天",
			text = "30级以上的野外地图会刷新怪物头目，靠近时根据雷达感应能够轻松找到，击杀可获得大量奖励！",
			awardicon = "tb_gaizaoshi，tb_tongyongzuangbei",
		},
		
}



tb.LimitedActTable = {
		[100009] = {
			id = 100009,
			name = "世界BOSS",
			priority = 1,
			type = 0,
			icon = "tb_tongyongzuangbei",
			level = 20,
			condition = 20,
			form = "单人/组队",
			award = "装备",
			show_name = "每天12:30，20:30",
			times_text = "不限",
			start_time = "12:30,20:30",
			text = "激情抢BOSS，获得极品神装，丰富奖励！",
			awardicon = "tb_zuanshi_wupin，tb_tongyongzuangbei，tb_suipianzhuangbei，tb_hongbaoshi_1",
		},
		
}